#pragma once
#include "FFMPEG_Stream.h"

class FFMPEG_VideoStream : public FFMPEG_Stream
{
public:
	void open(AVFormatContext* oc, AVDictionary* opt_arg) override;

	bool buildPacket(AVPacket& packet, AVFormatContext* oc);

	AVFrame* getFrame() override;

	void close() override;

private:
	void fill_yuv_image(AVFrame* pict, int frame_index, int width, int height);
	AVFrame* alloc_picture(enum AVPixelFormat pix_fmt, int width, int height);





	struct SwsContext* sws_ctx; /* ALLOCATION: Allocated independently:
								Only for video streams, and
								only when the pixel format generated by the stream is
								different to the pixel format set up for muxing. */

};