#pragma once
#include "FFMPEG_Stream.h"

class FFMPEG_VideoStream : public FFMPEG_Stream
{
public:
	FFMPEG_VideoStream()
		:
		FFMPEG_Stream{},
		sws_ctx{nullptr}
	{
	}

	void open(AVFormatContext* oc, AVDictionary* opt_arg) override;

	bool buildPacket(AVPacket& packet, AVFormatContext* oc);

	AVFrame* getFrame() override;

	void close() override;

protected:
	void setCodecContextParameters(const MuxerSettings & settings);

private:
	void fill_yuv_image(AVFrame* pict, int frame_index, int width, int height);
	AVFrame* alloc_picture(enum AVPixelFormat pix_fmt, int width, int height);

	/* ALLOCATION: Allocated independently:
							   Only for video streams, and
							   only when the pixel format generated by the stream is
							   different to the pixel format set up for muxing. */
	struct SwsContext* sws_ctx;
};